<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>0c663969-333e-4271-ad52-88c43b34cc4c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KobeKoi.DAL\KobeKoi.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Service\Admin\" />
    <Folder Include="Service\Organizer\" />
  </ItemGroup>

</Project>
